server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service-passenger-user?characterEncoding=utf8&useUnicode=true&serverTimezone=GMT&2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: myq1314666
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-passenger-user